### ISSUE TITLE
NTFS Protection triggers on whitespace in filepath on cloning

### ISSUE THREAD

**Issue by LeBraveLittleToaster** [Moritz-Steinle/TSF-Transformer-ARIMA-Comparison#1]
Describe the bug
The repository cannot be cloned under windows without removing ntfs protection under Windows OS. "Invalid path" is throwen for data in folder [/transformer/hyperparameter_study](https://github.com/Moritz-Steinle/TSF-Transformer-ARIMA-Comparison/tree/master/transformer/hyperparameter_study) 

To Reproduce

Clone on windows.

Expected behavior

Remove withspace from the three files in the aformentioned folder, then clone should work

Priority

Screenshots/Video
If applicable, add screenshots/video to help explain your problem. Remember to mark the area in the application thats impacted.

Desktop
OS: Windows
Architecture: x86 - AMD Ryzen

Additional context
-

Workaround:
After failed cloning, execute the following command in the then empty folder:
`git config core.protectNTFS false`
And pull again, then it works. However, can lead to errors on future commits, therefore, should only be used on read only.

**Comment by Moritz-Steinle** [comment]
Fixed by adding `_get_timestamp`which returns a timestamp in the format `dd-mm-yy_HH:MM:SS`
