### ISSUE TITLE
[Documentation] Not compatible Python 3.9 and 3.11, 3.12 not tested

### ISSUE THREAD

**Issue by LeBraveLittleToaster** [Moritz-Steinle/TSF-Transformer-ARIMA-Comparison#2]
Please add to README.md

**Python <= 3.9:**
_Incompatible due to language features from 3.10_

**Python >= 3.11:**
Not compatible due to pytorch-forecasting not compatible with > 3.10.

**Comment by Moritz-Steinle** [comment]
Added to Readme in ad57029
