### ISSUE TITLE
[Documentation] Credentials for database are not documented

### ISSUE THREAD

**Issue by LeBraveLittleToaster** [Moritz-Steinle/TSF-Transformer-ARIMA-Comparison#3]
Credentials are not documented, even though the example ini file provides the foundation for an educated guess :)

**Comment by Moritz-Steinle** [comment]
Added to Readme in https://github.com/Moritz-Steinle/TSF-Transformer-ARIMA-Comparison/commit/ad57029afdfb52df4c4a45f5a95017af4df7a89a

**Comment by Moritz-Steinle** [comment]
Added to Readme in https://github.com/Moritz-Steinle/TSF-Transformer-ARIMA-Comparison/commit/ad57029afdfb52df4c4a45f5a95017af4df7a89a
