### ISSUE TITLE
[Documentation] Fetch data before run

### ISSUE THREAD

**Issue by LeBraveLittleToaster** [Moritz-Steinle/TSF-Transformer-ARIMA-Comparison#4]
**Problem:**
Running main.py tries to load data which is not fetched yet. 

**Solution:**
Document the following or make it part of the main.py execution (if csvs are not there, fetch them).
I figured out, that the "main#fetch_data_from_db()" util function need to run before hand for each resolution. Then the csv´s are created and the prediction can run.

**Comment by Moritz-Steinle** [comment]
Fixed by adding the csv files to the repo and documenting how to fetch new data. https://github.com/Moritz-Steinle/TSF-Transformer-ARIMA-Comparison/commit/ad57029afdfb52df4c4a45f5a95017af4df7a89a

**Comment by Moritz-Steinle** [comment]
Fixed by adding the csv files to the repo and documenting how to fetch new data. https://github.com/Moritz-Steinle/TSF-Transformer-ARIMA-Comparison/commit/ad57029afdfb52df4c4a45f5a95017af4df7a89a
